name: Pipeline de 5 Fases (Arquitectura de Computadoras)

on:
  push:

jobs:
  IF:
    runs-on: ubuntu-latest
    steps:
      - name: Instruction Fetch
        run: |
          echo "Fase IF - Obteniendo instruccion desde memoria"
          sleep 3

  OF:
    needs: IF
    runs-on: ubuntu-latest
    steps:
      - name: Operand Fetch / Decode
        run: |
          echo "Fase OF - Decodificando instruccion y obteniendo operandos"
          sleep 3

  EX:
    needs: OF
    runs-on: ubuntu-latest
    steps:
      - name: Execute
        run: |
          echo "Fase EX - Ejecutando operacion en la ALU"
          sleep 3

  MEM:
    needs: EX
    runs-on: ubuntu-latest
    steps:
      - name: Memory Access
        run: |
          echo "Fase MEM - Accediendo a memoria si es necesario"
          sleep 3

  WB:
    needs: MEM
    runs-on: ubuntu-latest
    steps:
      - name: Write Back
        run: |
          echo "Fase WB - Escribiendo resultados en el registro"
          sleep 3

