name: Laboratorio de Pipeline Sistemicos

on: [push]

jobs:
  Compilacion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de codigo
        uses: actions/checkout@v4

      - name: Simulando Build
        run: echo "Compilando binarios..." && sleep 5

  Pruebas_Frontend:
    needs: Compilacion
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutando pruebas del Frontend
        run: echo "Validando Frontend..." && sleep 5

  Pruebas_Backend:
    needs: Compilacion
    runs-on: ubuntu-latest
    steps:
      - name: Ejecutando pruebas del Backend
        run: echo "Validando Backend..." && sleep 5
